### ISSUE TITLE
Question about calculation of absorption weight for target prompt

### ISSUE THREAD

**Issue by Haifeng3** [WangWenhao0716/TransHP#3]
TransHP is a great  work! I have a small question: when calculating the absorption weight of the target prompt using the self-attention mechanism, is the value calculated the average absorption weight of all feature tokens?
![1716956893988](https://github.com/WangWenhao0716/TransHP/assets/151635619/1ba754da-fc83-4d6b-a447-7f9f0de03b5f)

**Comment by WangWenhao0716** [comment]
Thanks for this insightful question. After checking, it seems that is correct. Since it has been quite a while (about 2 years) 
 since I finished this paper, I am not pretty sure :)

**Comment by Haifeng3** [comment]
thank you for your reply.
